#!/usr/bin/env python3
from __future__ import annotations

import argparse
import gzip
import json
import re
from collections import Counter
from pathlib import Path


DATA_PATH = Path("data/data.jsonl.gz")
REPORT_PATH = Path("scripts/spanish_languagetool_context_report.jsonl")


TOKEN_REPLACEMENTS = {
    # User-reviewed LanguageTool candidates.
    "alimpiada": "limpiada",
    "alimpiadas": "limpiadas",
    "alímpiada": "limpiada",
    "alimpiado": "limpiado",
    "alimpiados": "limpiados",
    "alimpiaduras": "limpiaduras",
    "alimpiador": "limpiador",
    "alimpiadero": "limpiadero",
    "mollidura": "mullidura",
    "frisol": "frijol",
    "frisoles": "frijoles",
    "frisolar": "frijolar",
    "asementado": "sementado",
    "asemillado": "semillado",
    "estropiezo": "tropiezo",
    "comprehendedor": "comprendedor",
    "comprehendida": "comprendida",
    "comprehenderla": "comprenderla",
    "ados": "a dos",
    "animalias": "animalías",
    "acevilarse": "acivilarse",
    "acevilado": "acivilado",
    "acevilizarse": "acivilizarse",
    # Current visible LanguageTool cluster, checked against parallel rows.
    "risar": "rifar",
    "estrañarse": "extrañarse",
    "enerisarse": "enerizarse",
    "desuelado": "desvelado",
    "frequentadamente": "frecuentemente",
    "frequentadas": "frecuentadas",
    "pocoa": "poco ha",
    "hínchir": "henchir",
    "hinchir": "henchir",
    "hechir": "henchir",
    "hencher": "henchir",
    "sunto": "sumo",
    # Remaining visible queue: high-confidence spelling, accent, and spacing fixes.
    "adivezorro": "adive, zorro",
    "anjeo": "angeo",
    "aresar": "arrasar",
    "arrojolo": "lo arrojó",
    "atronal": "atronar",
    "azoxarse": "enojarse",
    "cabellexo": "cabellera",
    "cacar": "cazar",
    "carirapado": "carirrapado",
    "cimientetia": "cementerio",
    "cogar": "colgar",
    "covardeser": "cobardecer (arcaico: ser cobarde)",
    "cuchillomángorrero": "cuchillo mangorrero",
    "declaralglosalexplical": "declarar, glosar, explicar",
    "deparerse": "depararse",
    "destomado": "deslomado",
    "disque": "dizque",
    "enciladopan": "ensilado",
    "encilarpan": "ensilar trigo así",
    "enjunto": "enjuto",
    "enojome": "me enojo",
    "enquanto": "en cuanto",
    "enalvardadavestia": "bestia enalbardada",
    "ensella": "encella",
    "granica": "granizar",
    "hamamache": "homarrache (arcaico: juglar)",
    "mienda": "mierda",
    "mosado": "mesado",
    "poser": "poseer",
    "putanear": "putañear (arcaico: fornicar)",
    "rechabar": "rechabar (arcaico: agriar)",
    "regasado": "arregazado",
    "reliquía": "reliquia",
    "retoso": "retozo",
    "romadisarse": "romadizarse (arcaico: tener catarro)",
    "tenazon": "tenazas",
    "tocer": "toser",
    "torsal": "torzal",
    "tratagar": "trafagar (arcaico: andar de una parte a otra)",
    "xauali": "jabalí",
    "atoño": "otoño",
    "añexarse": "anexarse",
    "escribanias": "escribanías",
    "lejia": "lejía",
    "magnanimamente": "magnánimamente",
    "maravedis": "maravedís",
    "melancolia": "melancolía",
    "melancolico": "melancólico",
    "pulmon": "pulmón",
    "regatoña": "regatona",
    "sinó": "sino",
    "tarantula": "tarántula",
    "visperas": "vísperas",
    "desearmuerte": "desear muerte",
    "escalentada": "calentada",
    "henchiralgo": "henchir algo",
    "nuevecientos": "novecientos",
    "cerraratapar": "cerrar o tapar",
    "accepillar": "acepillar",
    "acrencentar": "acrecentar",
    "aflixirse": "afligirse",
    "alludado": "ayudado",
    "alunbrar": "alumbrar",
    "anocheser": "anochecer",
    "aojafor": "aojador",
    "apedredor": "apedreador",
    "apuñaleado": "apuñalado",
    "arancar": "arrancar",
    "arancarse": "arrancarse",
    "arebatar": "arrebatar",
    "aredondear": "redondear",
    "argamasta": "argamasa",
    "artiyero": "artillero",
    "aspacio": "espacio",
    "asperesa": "aspereza",
    "atestimaguamento": "atestiguamiento",
    "azma": "asma",
    "azmatico": "asmático",
    "canbiar": "cambiar",
    "carrrasco": "carrasco",
    "caxcava": "cárcava",
    "cañaberal": "cañaveral",
    "chronista": "cronista",
    "concevido": "concebido",
    "conciderado": "considerado",
    "condicipulo": "condiscípulo",
    "cosinero": "cocinero",
    "crescerc": "crecer",
    "deante": "delante",
    "deasñudar": "desnudar",
    "defunto": "difunto",
    "desaventurado": "desventurado",
    "descernir": "discernir",
    "descocido": "descosido",
    "desembramecerse": "desembravecerse",
    "desinayar": "desmayar",
    "desinchar": "deshinchar",
    "desparamado": "desparramado",
    "desyervar": "desyerbar",
    "dispensero": "despensero",
    "docella": "doncella",
    "eclypsarse": "eclipsarse",
    "emfermero": "enfermero",
    "empelagameinto": "empalagamiento",
    "empolborearse": "empolvorarse",
    "empuxa": "empuja",
    "empuxador": "empujador",
    "enchirse": "henchirse",
    "ensensario": "incensario",
    "entonses": "entonces",
    "entormecerse": "entumecerse",
    "entristeserse": "entristecerse",
    "envermejecerse": "embermejecerse",
    "envira": "enviar",
    "ervazal": "herbazal",
    "escaravajo": "escarabajo",
    "escodriña": "escudriña",
    "escodriñador": "escudriñador",
    "esparsir": "esparcir",
    "espelusarse": "espeluzarse",
    "estropecar": "estropear",
    "exserado": "encerado",
    "favorecerdor": "favorecedor",
    "fengir": "fingir",
    "forsejar": "forcejar",
    "golocina": "golosina",
    "grangería": "granjería",
    "gygante": "gigante",
    "habahar": "avahar",
    "haraganez": "haraganes",
    "hilbanar": "hilvanar",
    "hostigamento": "hostigamiento",
    "imfamado": "infamado",
    "infuriado": "injuriado",
    "lanten": "llantén",
    "legia": "lejía",
    "magestad": "majestad",
    "malisiosamente": "maliciosamente",
    "marabillarse": "maravillarse",
    "maravilado": "maravillado",
    "menosprecial": "menospreciar",
    "moatrar": "mostrar",
    "molcaxete": "molcajete",
    "montaja": "mortaja",
    "nublano": "nublado",
    "offender": "ofender",
    "otolgar": "otorgar",
    "patriarcha": "patriarca",
    "pelozo": "peloso",
    "perzosamiente": "perezosamente",
    "poponer": "proponer",
    "pricionero": "prisionero",
    "primabera": "primavera",
    "pulzo": "pulso",
    "punsar": "punzar",
    "relanpagueal": "relampaguear",
    "remoliniar": "remolinar",
    "requebrajarse": "resquebrajarse",
    "resadores": "rezadores",
    "resar": "rezar",
    "resongar": "rezongar",
    "resquebraxarse": "resquebrajarse",
    "revaño": "rebaño",
    "reyueldo": "regüeldo",
    "rosedor": "roedor",
    "rosio": "rocío",
    "rraposa": "raposa",
    "sacerdosis": "sacerdocio",
    "sanpullido": "sarpullido",
    "saumar": "sahumar",
    "seiz": "seis",
    "sensillez": "sencillez",
    "serdo": "cerdo",
    "sietecientos": "setecientos",
    "sorbear": "sorber",
    "sorbervecerse": "ensoberbecerse",
    "sorver": "sorber",
    "sorvo": "sorbo",
    "sover": "sorber",
    "tavajas": "navajas",
    "taxar": "tasar",
    "testogo": "testigo",
    "uale": "vale",
    "uaron": "varón",
    "uiuda": "viuda",
    "uiudos": "viudos",
    "umilde": "humilde",
    "vazallaje": "vasallaje",
    "veodez": "beodez (arcaico: embriaguez)",
    "vergonsozo": "vergonzoso",
    "vergonzasamente": "vergonzosamente",
    "vexiga": "vejiga",
    "xaqueta": "chaqueta",
    "xarabe": "jarabe",
    "xitomate": "jitomate",
    "yusticiar": "ajusticiar",
    "zorrilllo": "zorrillo",
    # Same reviewed clusters.
    "guedeia": "guedeja",
    "emmarañada": "enmarañada",
    "descerrugado": "descervigado",
    "énuarado": "envarado",
    # Fused forms whose root is valid Spanish dolar 'desbastar/labrar'.
    "dolaralgo": "dolar algo",
    # Next visible cluster: direct spelling and fused-form fixes.
    "alogro": "a logro",
    "desgusto": "disgusto",
    "desto": "de esto",
    "desuario": "desvarío",
    "elar": "helar",
    "herviente": "hirviente",
    "pecilgo": "pellizco",
    "pixa": "pija",
    "quele": "que le",
    "soberbecerse": "ensoberbecerse",
    "agorear": "agorar",
    "apezgar": "apesgar",
    "endar": "en dar",
    "enquatro": "en cuatro",
    "dequatro": "de cuatro",
    "niygual": "ni igual",
    # Next visible cluster: mostly old orthography with clear modern forms.
    "acucharrada": "acucharada",
    "arojar": "arrojar",
    "atericiado": "ictericiado",
    "avna": "a una",
    "corua": "corva",
    "encensado": "incensado",
    "exear": "oxear",
    "eñel": "en el",
    "falza": "falsa",
    "haragania": "haraganería",
    "hechan": "echan",
    "hechando": "echando",
    "inabil": "inhábil",
    "javali": "jabalí",
    "magánta": "maganta",
    "mazoral": "mazorral",
    "meloxa": "meloja",
    "mescla": "mezcla",
    "mesclada": "mezclada",
    "micericordia": "misericordia",
    "mollida": "mullida",
    "moxca": "mosca",
    "moxcas": "moscas",
    "moxcada": "moscada",
    "negosio": "negocio",
    "nequén": "henequén",
    "nieblina": "neblina",
    "ocidental": "occidental",
    "oluidado": "olvidado",
    "padese": "padece",
    "pleveya": "plebeya",
    "poluos": "polvos",
    "proverse": "proveerse",
    "rosiar": "rociar",
    "sugeto": "sujeto",
    "tiguere": "tigre",
    "trahe": "trae",
    "vañar": "bañar",
    "vaño": "baño",
    "xabonar": "jabonar",
    "xeme": "jeme",
    "xicara": "jícara",
    "xicaras": "jícaras",
    # Next visible 5-count cluster: direct modern spellings and fused forms.
    "acorrucandose": "acurrucándose",
    "anocher": "anochecer",
    "apechos": "a pecho",
    "aqual": "a cuál",
    "atodas": "a todas",
    "atratar": "a tratar",
    "aucente": "ausente",
    "caruonero": "carbonero",
    "caxcar": "cascar",
    "cenogil": "cenojil",
    "cheremia": "chirimía",
    "chiminea": "chimenea",
    "cieruo": "ciervo",
    "cobdicioso": "codicioso",
    "concentir": "consentir",
    "corcoba": "corcova",
    "coxcorron": "coscorrón",
    "debuxada": "dibujada",
    "dende": "desde",
    "desapercebido": "desapercibido",
    "desempedagor": "desempedrador",
    "desonestas": "deshonestas",
    "desotra": "de esa otra",
    "desuanecer": "desvanecer",
    "desuelarse": "desvelarse",
    "desvaratada": "desbaratada",
    "differente": "diferente",
    "disfrasado": "disfrazado",
    "ditado": "dictado",
    "divinación": "adivinación",
    "eclipsi": "eclipse",
    "emmudecer": "enmudecer",
    "emméndada": "enmendada",
    "encensar": "incensar",
    "encoruar": "encorvar",
    "eneste": "en este",
    "entresi": "entre sí",
    "entretexida": "entretejida",
    "entretexido": "entretejido",
    "entricada": "intrincada",
    "envegecer": "envejecer",
    "enxalzar": "ensalzar",
    "esaminada": "examinada",
    "escojer": "escoger",
    "escopir": "escupir",
    "escusandose": "excusándose",
    "espendiendo": "expendiendo",
    "espremida": "exprimida",
    "espremido": "exprimido",
    "estorvo": "estorbo",
    "estremada": "extremada",
    "executar": "ejecutar",
    "fortunado": "afortunado",
    "friscal": "fiscal",
    "fructa": "fruta",
    "garvanzos": "garbanzos",
    "geme": "jeme",
    "ginetear": "jinetear",
    "hade": "ha de",
    "hagome": "me hago",
    "haser": "hacer",
    "herege": "hereje",
    "hidionda": "hedionda",
    "hortiga": "ortiga",
    "libiana": "liviana",
    "madexa": "madeja",
    "magestuosa": "majestuosa",
    "mancedumbre": "mansedumbre",
    "masorca": "mazorca",
    "mestruo": "menstruo",
    "mollido": "mullido",
    "mordificar": "mordiscar",
    "moxcatel": "moscatel",
    "muchacherria": "muchachería",
    "muger": "mujer",
    "nuve": "nube",
    "omenaje": "homenaje",
    "onesta": "honesta",
    "pecilgar": "pecilgar (arcaico: pellizcar)",
    "pluvia": "lluvia",
    "porlo": "por lo",
    "portatile": "portátil",
    "provada": "probada",
    "ranaquajo": "renacuajo",
    "rebatada": "arrebatada",
    "rebenton": "reventón",
    "recompenzar": "recompensar",
    "recoxer": "recoger",
    "redondes": "redondez",
    "regazado": "arregazado",
    "remanzo": "remanso",
    # Next visible 5-count cluster.
    "resurrection": "resurrección",
    "rompida": "rota",
    "rovar": "robar",
    "rreal": "real",
    "saluo": "salvo",
    "sepulchro": "sepulcro",
    "seruido": "servido",
    "sincel": "cincel",
    "sincelar": "cincelar",
    "soberuiamente": "soberbiamente",
    "suabe": "suave",
    "torondon": "tolondrón",
    "torondones": "tolondrones",
    "torondrones": "tolondrones",
    "troupiale": "trupial",
    "tverto": "tuerto",
    "valet": "ayuda de cámara",
    "vandear": "bandear",
    "varandas": "barandas",
    "verguensa": "vergüenza",
    "vidro": "vidrio",
    "visage": "visaje",
    "xaguei": "jagüey",
    "xicalas": "jícaras",
    "yezo": "yeso",
    # Next visible 4-count cluster: direct spelling/fused-form fixes,
    # excluding source/Nahuatl/proper-domain tokens and context-only cases.
    "aalgun": "a algún",
    "aalguno": "a alguno",
    "aciprés": "ciprés",
    "aconocer": "a conocer",
    "adellantada": "adentellada",
    "aderechas": "a derechas",
    "aderesarse": "aderezarse",
    "aduersidades": "adversidades",
    "advervio": "adverbio",
    "afliction": "aflicción",
    "aflijido": "afligido",
    "afloxandoles": "aflojándoles",
    "alagueño": "halagüeño",
    "alagueños": "halagüeños",
    "halagueñas": "halagüeñas",
    "alajas": "alhajas",
    "alanzada": "lanzada",
    "alholi": "alfolí",
    "alinpiar": "limpiar",
    "aluanega": "albanega",
    "aluergarse": "albergarse",
    "alvergarse": "albergarse",
    "amanese": "amanece",
    "amanesido": "amanecido",
    "anelar": "anhelar",
    "anzar": "ánsar",
    "apercivido": "apercibido",
    "aperder": "a perder",
    "arrazar": "arrasar",
    "arrodelado": "arrodalado",
    "asaber": "a saber",
    "atiempos": "a tiempos",
    "atraher": "atraer",
    "atravillados": "atraillados",
    "avdiencia": "audiencia",
    "avergonsarse": "avergonzarse",
    "axuar": "ajuar",
    "cabezcaido": "cabizcaído",
    "cadavno": "cada uno",
    "caluniado": "calumniado",
    "captivado": "cautivado",
    "caver": "caber",
    "canpanas": "campanas",
    "canpanilla": "campanilla",
    "cavesa": "cabeza",
    "caxcajo": "cascajo",
    "christalina": "cristalina",
    "codisiada": "codiciada",
    "concegil": "concejil",
    "concideración": "consideración",
    "condecender": "condescender",
    "congosa": "congoja",
    "conjunctiones": "conjunciones",
    "conserua": "conserva",
    "convatir": "combatir",
    "covardia": "cobardía",
    "debatalla": "de batalla",
    "delexos": "de lejos",
    "depunta": "de punta",
    "desapercivido": "desapercibido",
    "desboronada": "desmoronada",
    "desembolberse": "desenvolverse",
    "deseredado": "desheredado",
    "desmenusar": "desmenuzar",
    "desonrarse": "deshonrarse",
    "despedasando": "despedazando",
    "desuariadamente": "desvariadamente",
    "devia": "debía",
    "difficultad": "dificultad",
    "diligeute": "diligente",
    "dvda": "duda",
    "elbocado": "el bocado",
    "election": "elección",
    "eloquente": "elocuente",
    "emmallar": "enmallar",
    "emmohecerse": "enmohecerse",
    "emos": "hemos",
    "empuxones": "empujones",
    "encaxar": "encajar",
    "enhadarme": "enfadarme",
    "enmi": "en mi",
    "ensobervecerse": "ensoberbecerse",
    "ensusiada": "ensuciada",
    "entibiamento": "entibiamiento",
    "entiviado": "entibiado",
    "entiviarse": "entibiarse",
    "enuasar": "envasar",
    "envegaserse": "envejecerse",
    "enxabonamiento": "enjabonamiento",
    "enxabonamiénto": "enjabonamiento",
    "enxaluegado": "enjalbegado",
    "enxambre": "enjambre",
    "enxugado": "enjugado",
    "enxundia": "enjundia",
    "enxuta": "enjuta",
    "erbolario": "herbolario",
    "eregia": "herejía",
    "esamen": "examen",
    "esaminar": "examinar",
    "escova": "escoba",
    "escrivania": "escribanía",
    "esecutar": "ejecutar",
    "esforcar": "esforzar",
    "esparse": "esparce",
    "espedir": "expedir",
    "espexo": "espejo",
    "estenderme": "extenderme",
    "estremidades": "extremidades",
    "facilcosa": "fácil cosa",
    "feros": "feroz",
    "floreton": "floretón",
    "frecha": "flecha",
    "garavato": "garabato",
    "gentilizmo": "gentilismo",
    "geringa": "jeringa",
    "gomitada": "vomitada",
    "graza": "grasa",
    "guedijudo": "guedejudo",
    "haverselo": "habérselo",
    "honrrosamente": "honrosamente",
    "inobidiente": "inobediente",
    "insufficiente": "insuficiente",
    "iten": "ítem",
    "lenterna": "linterna",
    # Next visible cluster: direct modern spellings.
    "deservado": "desyerbado",
    "lienso": "lienzo",
    "luxuriosamente": "lujuriosamente",
    "martilogio": "martirologio",
    "mensagero": "mensajero",
    "morcielago": "murciélago",
    "mostruo": "monstruo",
    "mucico": "músico",
    "oaya": "o aya",
    "ocidente": "occidente",
    "ocosas": "o cosas",
    "oluido": "olvido",
    "omierda": "o mierda",
    "ortelano": "hortelano",
    "ospedarse": "hospedarse",
    "ostinarse": "obstinarse",
    "parentezco": "parentesco",
    "pasagero": "pasajero",
    "pavellon": "pabellón",
    "peruerso": "perverso",
    "picina": "piscina",
    "pizon": "pisón",
    "prover": "proveer",
    "quexandose": "quejándose",
    "recebidos": "recibidos",
    "redemptor": "redentor",
    "restrañar": "restañar",
    "resusitar": "resucitar",
    "revosar": "rebosar",
    "rofian": "rufián",
    "ronqueria": "ronquera",
    "sanja": "zanja",
    "senisa": "ceniza",
    "satisfecer": "satisfacer",
    "scevon": "cebón",
    "sobervio": "soberbio",
    "solibiar": "soliviar",
    "sulco": "surco",
    "tectorica": "retórica",
    "tenebregoso": "tenebroso",
    "tericia": "tiricia",
    # Next visible 3- and 4-count clusters: direct modern spellings,
    # fused forms, and accent restoration. Context-only/source tokens stay out.
    "accelerado": "acelerado",
    "acceptando": "aceptando",
    "acomer": "a comer",
    "aderesado": "aderezado",
    "aderesar": "aderezar",
    "adeseo": "a deseo",
    "adesora": "a deshora",
    "adestajo": "a destajo",
    "adovar": "adobar",
    "aduenedizos": "advenedizos",
    "aduersario": "adversario",
    "aella": "a ella",
    "affirmando": "afirmando",
    "afligendo": "afligiendo",
    "afloxada": "aflojada",
    "afulano": "a fulano",
    "aglo": "algo",
    "ahermosear": "hermosear",
    "ajornal": "a jornal",
    "alcade": "alcalde",
    "algusto": "al gusto",
    "almodo": "al modo",
    "aluerca": "alberca",
    "amanderecha": "a mano derecha",
    "anosotros": "a nosotros",
    "arraygar": "arraigar",
    "arto": "harto",
    "artar": "hartar",
    "asepillada": "acepillada",
    "asosegado": "sosegado",
    "asufre": "azufre",
    "aseleración": "aceleración",
    "aucentarse": "ausentarse",
    "avil": "hábil",
    "ayúntán": "ayuntan",
    "cavalleriza": "caballeriza",
    "caxcada": "cascada",
    "caxcos": "cascos",
    "cayga": "caiga",
    "cevado": "cebado",
    "cevon": "cebón",
    "cevo": "cebo",
    "chrismado": "crismado",
    "chrismar": "crismar",
    "chronica": "crónica",
    "cibdadano": "ciudadano",
    "circunspection": "circunspección",
    "cobdiciada": "codiciada",
    "cobrir": "cubrir",
    "coje": "coge",
    "comprativo": "comparativo",
    "congeturar": "conjeturar",
    "congoxado": "congojado",
    "contradición": "contradicción",
    "conualecencia": "convalecencia",
    "conualecido": "convalecido",
    "conuersable": "conversable",
    "conuéncido": "convencido",
    "cosear": "cocear",
    "cosiendolas": "cosiéndolas",
    "coxer": "coger",
    "cresiente": "creciente",
    "cudicia": "codicia",
    "cudiciar": "codiciar",
    "cuerbo": "cuervo",
    "cónlas": "con las",
    "cónlos": "con los",
    "cónueniente": "conveniente",
    "debarro": "de barro",
    "decamaras": "de cámaras",
    "dedia": "de día",
    "delana": "de lana",
    "delcuello": "del cuello",
    "deletras": "de letras",
    "demercado": "de mercado",
    "depresto": "de presto",
    "despaldas": "de espaldas",
    "derrivado": "derribado",
    "desapercevido": "desapercibido",
    "desarna": "de sarna",
    "descarrear": "descarriar",
    "descaxcadas": "descascadas",
    "descobierta": "descubierta",
    "descrecer": "decrecer",
    "desdesirse": "desdecirse",
    "desembrabecido": "desembravecido",
    "desencasado": "desencajado",
    "desenuaynar": "desenvainar",
    "deseredar": "desheredar",
    "deserrajar": "descerrajar",
    "desgovernado": "desgobernado",
    "desgovernar": "desgobernar",
    "deshervar": "desherbar",
    "desménbrar": "desmembrar",
    "desperdisiar": "desperdiciar",
    "desperesarse": "desperezarse",
    "desquartizar": "descuartizar",
    "desuelar": "desvelar",
    "desuiar": "desviar",
    "detodas": "de todas",
    "deverguensa": "de vergüenza",
    "devilitado": "debilitado",
    "devnos": "de unos",
    "devo": "debo",
    "dibulgar": "divulgar",
    "disfama": "difama",
    "echicero": "hechicero",
    "elpan": "el pan",
    "emmaderada": "enmaderada",
    "emmaxcarar": "enmascarar",
    "emmudecerse": "enmudecerse",
    "emméndar": "enmendar",
    "empedernecida": "empedernida",
    "empesar": "empezar",
    "empie": "en pie",
    "enalto": "en alto",
    "encensario": "incensario",
    "encierta": "en cierta",
    "encoruarse": "encorvarse",
    "piedrera": "pedrera",
    "rrosa": "rosa",
    "traher": "traer",
    "travajar": "trabajar",
    "ubas": "uvas",
    "usavan": "usaban",
    "vaguidos": "vahídos",
    "vallesta": "ballesta",
    "vallestero": "ballestero",
    "vanderas": "banderas",
    "vatalla": "batalla",
    "vedriero": "vidriero",
    "vellaquerias": "bellaquerías",
    "vertos": "versos",
    "visages": "visajes",
    "vándo": "bando",
    "xabonero": "jabonero",
    "xaguey": "jagüey",
    "xara": "jara",
    "yemplearse": "y emplearse",
    "yuntura": "juntura",
    "zoga": "soga",
    "zunbar": "zumbar",
    "cónsumir": "consumir",
    "oel": "o el",
    "yua": "iba",
    "dandose": "dándose",
    # Larger family pass: recurrent old orthography in non-Wimmer sources.
    "alpunto": "al punto",
    "cabador": "cavador",
    "carienxuto": "carienjuto",
    "concernada": "con cernada",
    "decuenta": "de cuenta",
    "desenetrarse": "desenredarse",
    "desparto": "de esparto",
    "encoxido": "encogido",
    "encrusijada": "encrucijada",
    "encuenta": "en cuenta",
    "endos": "en dos",
    "enechizar": "hechizar",
    "enegreser": "ennegrecer",
    "enlabiamiénto": "enlabiamiento",
    "enloquese": "en lo que se",
    "enplumar": "emplumar",
    "ensi": "en sí",
    "ensobervecido": "ensoberbecido",
    "entodo": "en todo",
    "entomecida": "entumecida",
    "entretexendo": "entretejiendo",
    "enuegecida": "envejecida",
    "enuegecido": "envejecido",
    "enxaluegada": "enjalbegada",
    "enxalzado": "ensalzado",
    "enxertarle": "injertarle",
    "erencia": "herencia",
    "escarvada": "escarbada",
    "escarvandola": "escarbándola",
    "escojido": "escogido",
    "escortar": "escotar",
    "escrebir": "escribir",
    "escrevir": "escribir",
    "escripta": "escrita",
    "espantadisa": "espantadiza",
    "espasiosa": "espaciosa",
    "espinaso": "espinazo",
    "estendiendo": "extendiendo",
    "esteriormente": "exteriormente",
    "esteriorménte": "exteriormente",
    "estibal": "estival",
    "estorua": "estorba",
    "estranjero": "extranjero",
    "estrivo": "estribo",
    "exceciva": "excesiva",
    "exemplar": "ejemplar",
    "faysan": "faisán",
    "floxamente": "flojamente",
    "fluxo": "flujo",
    "ginete": "jinete",
    "govierno": "gobierno",
    "grangero": "granjero",
    "granzar": "graznar",
    "gueso": "hueso",
    "guzanos": "gusanos",
    "hasedor": "hacedor",
    "haverlo": "haberlo",
    "heche": "eche",
    "heroyca": "heroica",
    "hierue": "hierve",
    "hiluanar": "hilvanar",
    "hinchendo": "hinchiendo",
    "hogera": "hoguera",
    "honrroso": "honroso",
    "hornamentos": "ornamentos",
    "immortal": "inmortal",
    "inconuesable": "inconversable",
    "instrumeuto": "instrumento",
    "interuallo": "intervalo",
    "interualo": "intervalo",
    "ladrilleria": "ladrillería",
    "letor": "lector",
    "lidear": "lidiar",
    "lisongeado": "lisonjeado",
    "lizonjear": "lisonjear",
    "lombris": "lombriz",
    "lomismo": "lo mismo",
    "macisa": "maciza",
    "maestradgo": "maestrazgo",
    "maestrasgo": "maestrazgo",
    "maior": "mayor",
    "malencolia": "melancolía",
    "mananteal": "manantial",
    "manza": "mansa",
    "manzo": "manso",
    "marhojo": "marojo",
    "masmorra": "mazmorra",
    "matavan": "mataban",
    "mestruar": "menstruar",
    "miral": "mirar",
    "mosa": "moza",
    "mvchas": "muchas",
    "nabajas": "navajas",
    "nasce": "nace",
    "neglicencia": "negligencia",
    "nieruos": "nervios",
    "noatada": "no atada",
    "nole": "no le",
    "nolo": "no lo",
    "nosea": "no sea",
    "oluidarse": "olvidarse",
    "ostinar": "obstinar",
    "otubre": "octubre",
    "papadgo": "papazgo",
    "pasciencia": "paciencia",
    "paxa": "paja",
    "peresca": "perezca",
    "peresozo": "perezoso",
    "pezar": "pesar",
    "pezcar": "pescar",
    "piesa": "pieza",
    "piez": "pies",
    "pifaro": "pífano",
    "polborear": "polvorear",
    "polbos": "polvos",
    "polida": "pulida",
    "polido": "pulido",
    "poluorear": "polvorear",
    "polution": "polución",
    "porel": "por el",
    "poresos": "por esos",
    "porende": "por ende",
    "porquanto": "por cuanto",
    "portanto": "por tanto",
    "precencia": "presencia",
    "presumpción": "presunción",
    "proprios": "propios",
    "prostrandose": "postrándose",
    "provanza": "probanza",
    "prueva": "prueba",
    "puncar": "punzar",
    "púnsar": "punzar",
    "razo": "raso",
    "rebendedor": "revendedor",
    "rebidar": "revidar",
    "rebienta": "revienta",
    "recebimiénto": "recibimiento",
    "recocijada": "regocijada",
    "reembidar": "reenvidar",
    "refitorio": "refectorio",
    "reléntecer": "relentecer",
    "rempuxon": "empujón",
    "reprehenden": "reprenden",
    "resualando": "resbalando",
    "resvalando": "resbalando",
    "resvalar": "resbalar",
    "retaxado": "retajado",
    "risando": "rifando",
    "rofianear": "rufianear",
    "rraíz": "raíz",
    "rrey": "rey",
    "rrosal": "rosal",
    "rugado": "arrugado",
    "sacrificavan": "sacrificaban",
    "saltamonte": "saltamontes",
    "sanctificar": "santificar",
    "sant": "san",
    "sasonar": "sazonar",
    "sentella": "centella",
    "servisio": "servicio",
    "sesta": "sexta",
    "siniestero": "siniestro",
    "sobervecerse": "ensoberbecerse",
    "sobervias": "soberbias",
    "soberviamente": "soberbiamente",
    "sobresi": "sobre sí",
    "sorue": "sorbe",
    "sorve": "sorbe",
    "soruible": "sorbible",
    "sorvible": "sorbible",
    "sospirar": "suspirar",
    "sotiles": "sutiles",
    "spiritu": "espíritu",
    "sujuntivo": "subjuntivo",
    "sumptuosa": "suntuosa",
    "tenblar": "temblar",
    "tienese": "tiénese",
    "tomal": "tomar",
    "torvellino": "torbellino",
    "travajo": "trabajo",
    "travazon": "trabazón",
    "uerfano": "huérfano",
    "umana": "humana",
    "umedecer": "humedecer",
    "usansa": "usanza",
    "vayna": "vaina",
    "veen": "ven",
    "valancear": "balancear",
    "vellota": "bellota",
    "verfano": "huérfano",
    "vesino": "vecino",
    "vesped": "huésped",
    "vistuario": "vestuario",
    "vizco": "bizco",
    "viñendo": "viniendo",
    "volos": "bolos",
    "voluer": "volver",
    "xabón": "jabón",
    "xergon": "jergón",
    # Count-2 layer: high-confidence old orthography and fused particles.
    "aalgúna": "a alguna",
    "acceptada": "aceptada",
    "adiez": "a diez",
    "adminstrar": "administrar",
    "adornavan": "adornaban",
    "aduerbi": "adverbio",
    "advbio": "adverbio",
    "advierbo": "adverbio",
    "adéntelladas": "adentelladas",
    "aechaduras": "ahechaduras",
    "aechar": "ahechar",
    "aempellones": "a empellones",
    "afijido": "afligido",
    "aflijir": "afligir",
    "afloxado": "aflojado",
    "agrabiarse": "agraviarse",
    "aguilocho": "aguilucho",
    "aguzarel": "aguzar el",
    "ajuego": "a juego",
    "alboles": "árboles",
    "alcaguete": "alcahuete",
    "aldava": "aldaba",
    "alexarse": "alejarse",
    "aliaua": "aljaba",
    "alibiar": "aliviar",
    "alimpiamento": "limpiamiento",
    "aloquese": "a lo que se",
    "altorno": "al torno",
    "aluor": "albor",
    "alvanega": "albanega",
    "amandar": "a mandar",
    "amarilles": "amarillez",
    "amarillicerse": "amarillecerse",
    "amarrillecerse": "amarillecerse",
    "amazar": "amasar",
    "antantier": "anteantier",
    "apedazos": "a pedazos",
    "apercivirse": "apercibirse",
    "apezgada": "apesgada",
    "apollar": "apoyar",
    "aporfia": "a porfía",
    "aprobechar": "aprovechar",
    "apropriarse": "apropiarse",
    "aprovada": "aprobada",
    "aprovar": "aprobar",
    "aqualparte": "a cuál parte",
    "aquexarse": "aquejarse",
    "argamaza": "argamasa",
    "arrevatada": "arrebatada",
    "arros": "arroz",
    "arrónjada": "arrojada",
    "asatear": "asaetear",
    "asechandole": "acechándole",
    "aserrer": "a serrar",
    "aseteado": "asaeteado",
    "atabiarse": "ataviarse",
    "atal": "a tal",
    "ataval": "atabal",
    "atisar": "atizar",
    "atiémpos": "a tiempos",
    "atordir": "aturdir",
    "atoyado": "atollado",
    "atraversar": "atravesar",
    "atraversarse": "atravesarse",
    "atuertas": "a tuertas",
    "aucentes": "ausentes",
    "avenedizo": "advenedizo",
    "averse": "haberse",
    "avibado": "avivado",
    "avituarse": "habituarse",
    "axenxos": "ajenjos",
    "ayntada": "ayuntada",
    "aytarse": "ahitarse",
    "azagan": "azacán",
    "azaltear": "asaetear",
    "azco": "asco",
    "azutea": "azotea",
    "cabezbajo": "cabizbajo",
    "caci": "casi",
    "cadaro": "catarro",
    "caluniar": "calumniar",
    "camiza": "camisa",
    "camodar": "acomodar",
    "campollano": "campo llano",
    "captivo": "cautivo",
    "carmeci": "carmesí",
    "cavalgar": "cabalgar",
    "cavallerizo": "caballerizo",
    "caxcajal": "cascajal",
    "caxcarse": "cascarse",
    "cayar": "callar",
    "ceruuno": "cervuno",
    "cexar": "cejar",
    "chapatear": "chapotear",
    "chismeria": "chismería",
    "cibdades": "ciudades",
    "ciminterio": "cementerio",
    "cinquenta": "cincuenta",
    "cobdiciado": "codiciado",
    "coberton": "cobertor",
    "cochillada": "cuchillada",
    "codornis": "codorniz",
    "cojon": "cojón",
    "congoxojo": "congojoso",
    "congoxosamente": "congojosamente",
    "congoxoso": "congojoso",
    "coniunction": "conjunción",
    "conlazo": "con lazo",
    "conotro": "con otro",
    "conprar": "comprar",
    "consegil": "concejil",
    "consertado": "concertado",
    "contracto": "contrato",
    "conueniencia": "conveniencia",
    "conuersar": "conversar",
    "convatida": "combatida",
    "corer": "correr",
    "coronper": "corromper",
    "correjir": "corregir",
    "coxcoja": "coscoja",
    "coxera": "cojera",
    "coxin": "cojín",
    "crescer": "crecer",
    "criva": "criba",
    "crivar": "cribar",
    "crucifixo": "crucifijo",
    "cruximiénto": "crujimiento",
    "cudicioso": "codicioso",
    "cueba": "cueva",
    "cuerzo": "corzo",
    "cuese": "cuece",
    "cueyo": "cuello",
    "cuvierta": "cubierta",
    "cuviertas": "cubiertas",
    "cvaderno": "cuaderno",
    "cómbidados": "convidados",
    "cómbite": "convite",
    "cónalguno": "con alguno",
    "cóndecendiendo": "condescendiendo",
    "cóngoxosa": "congojosa",
    "cónjúnctión": "conjunción",
    "cónuertimiénto": "convertimiento",
    "dadivozo": "dadivoso",
    "darriba": "de arriba",
    "davida": "dádiva",
    "dealgun": "de algún",
    "deartilleria": "de artillería",
    "deboda": "de boda",
    "decamino": "de camino",
    "decasa": "de casa",
    "decear": "desear",
    "deentender": "de entender",
    "defuncto": "difunto",
    "delabada": "deslavada",
    "delgades": "delgadez",
    "deloqueno": "de lo que no",
    "demandandor": "demandador",
    "demasada": "demasiada",
    "demiel": "de miel",
    "depluma": "de pluma",
    "deprende": "aprende",
    "depresente": "de presente",
    "desabaratado": "desbaratado",
    "desarraygado": "desarraigado",
    "desasociego": "desasosiego",
    "desauciado": "desahuciado",
    "desbarratar": "desbaratar",
    "desconsertar": "desconcertar",
    "desconsertarse": "desconcertarse",
    "descoraznarse": "descorazonarse",
    "desembainar": "desenvainar",
    "desembolber": "desenvolver",
    "desembolvedor": "desenvolvedor",
    "desenetrada": "desenredada",
    "desenetrar": "desenredar",
    "desentonamiéto": "desentonamiento",
    "desenuainada": "desenvainada",
    "desenuainar": "desenvainar",
    "desenuaynada": "desenvainada",
    "deserrajada": "descerrajada",
    "deservar": "desyerbar",
    "desfaxar": "desfajar",
    "desminuida": "disminuida",
    "desménbrado": "desmembrado",
    "desollo": "desolló",
    "desonrrar": "deshonrar",
    "despedasado": "despedazado",
    "despedirce": "despedirse",
    "desquartizada": "descuartizada",
    "desrengado": "derrengado",
    "desrrabada": "desrabada",
    "desuariada": "desvariada",
    "desuariado": "desvariado",
    "desuestir": "desvestir",
    "desvaratado": "desbaratado",
    "desvearse": "desviarse",
    "desvergonsarse": "desvergonzarse",
    "detarde": "de tarde",
    "deteta": "de teta",
    "deun": "de un",
    "devaca": "de vaca",
    "devajo": "debajo",
    "deve": "debe",
    "deveinte": "de veinte",
    "devéntana": "de ventana",
    "dezatar": "desatar",
    "dicernir": "discernir",
    "differentes": "diferentes",
    "difinido": "definido",
    "disfamación": "difamación",
    "disminasando": "desmenuzando",
    "distilación": "destilación",
    "dolente": "doliente",
    "dotrina": "doctrina",
    "dubdoso": "dudoso",
    "ecclesiastico": "eclesiástico",
    "ecclesiasticos": "eclesiásticos",
    "ecleciasticas": "eclesiásticas",
    "eclypse": "eclipse",
    "eclypzar": "eclipsar",
    "elcánto": "el canto",
    "elvarón": "el varón",
    "emendado": "enmendado",
    "emmellar": "mellar",
    "emmendada": "enmendada",
    "emmiende": "enmiende",
    "emor": "error",
    "empedernecido": "empedernido",
    "empedir": "impedir",
    "empobreserse": "empobrecerse",
    "empoluorado": "empolvorado",
    "empoluorar": "empolvorar",
    "empoluorearse": "empolvorarse",
    "empozoñado": "emponzoñado",
    "empozoñar": "emponzoñar",
    # Next layer: accents, fused particles, and direct old-spelling fixes.
    "acompañandolo": "acompañándolo",
    "aflojea": "afloja",
    "agoreria": "agorería",
    "agusar": "aguzar",
    "alboles": "árboles",
    "alapostre": "a la postre",
    "alcaidia": "alcaidía",
    "alomenos": "a lo menos",
    "amano": "a mano",
    "apocandose": "apocándose",
    "apartandose": "apartándose",
    "apitonamiénto": "apitonamiento",
    "arabigo": "arábigo",
    "arrancandolo": "arrancándolo",
    "arrastrán": "arrastran",
    "artifice": "artífice",
    "asimiénto": "asimiento",
    "asmatico": "asmático",
    "asperamente": "ásperamente",
    "atavio": "atavío",
    "aventurajado": "aventajado",
    "avisandole": "avisándole",
    "azofar": "azófar",
    "caerseme": "caérseme",
    "catedra": "cátedra",
    "chapineria": "chapinería",
    "chirimia": "chirimía",
    "clavazon": "clavazón",
    "clerigos": "clérigos",
    "cobardia": "cobardía",
    "coce": "cocea",
    "codicién": "codicien",
    "comilon": "comilón",
    "confian": "confían",
    "corrómpido": "corrompido",
    "cosmografia": "cosmografía",
    "cuéntas": "cuentas",
    "cómbatir": "combatir",
    "cómpetir": "competir",
    "cómpone": "compone",
    "cónsciéncia": "conciencia",
    "cónsultar": "consultar",
    "debia": "debía",
    "dentra": "dentro",
    "derredón": "de redón",
    "derrendón": "de rendón",
    "desafio": "desafío",
    "desleida": "desleída",
    "desleirse": "desleírse",
    "desmenuzamiénto": "desmenuzamiento",
    "desmenuzandola": "desmenuzándola",
    "despúntada": "despuntada",
    "desvarios": "desvaríos",
    "determinadaménte": "determinadamente",
    "diligentisimo": "diligentísimo",
    "doliénte": "doliente",
    "dándo": "dando",
    "eclesiasticas": "eclesiásticas",
    "eclesiastico": "eclesiástico",
    "echandolas": "echándolas",
    "echándo": "echando",
    "empuxandolo": "empujándolo",
    "enagenada": "enajenada",
    "enalgun": "en algún",
    "enalgo": "en algo",
    "encaxado": "encajado",
    "encieno": "en cieno",
    "enclabar": "enclavar",
    "encomendandolo": "encomendándolo",
    "encoméndar": "encomendar",
    "encompañia": "en compañía",
    "encoraginarse": "encorajinarse",
    "encurvado": "encorvado",
    "enderesar": "enderezar",
    "endulsar": "endulzar",
    "enestár": "enestar",
    "enfasis": "énfasis",
    "enfriamiénto": "enfriamiento",
    "enguerra": "en guerra",
    "enhórabuena": "enhorabuena",
    "enhorcado": "ahorcado",
    "enjuego": "en juego",
    "enmojo": "en remojo",
    "ennegrar": "ennegrecer",
    "enpacho": "empacho",
    "enpedir": "impedir",
    "enpoco": "en poco",
    "enpolvorado": "empolvorado",
    "ensangréntarse": "ensangrentarse",
    "ensoberveserse": "ensoberbecerse",
    "ensus": "en sus",
    "entantos": "en tantos",
    "enterminos": "en términos",
    "entiendese": "entiéndese",
    "enténdiendo": "entendiendo",
    "entorpecimiénto": "entorpecimiento",
    "entretexedor": "entretejedor",
    "entricadamente": "intrincadamente",
    "enuarada": "envarada",
    "envegecida": "envejecida",
    "envegeserse": "envejecerse",
    "engañosaménte": "engañosamente",
    "enxabonada": "enjabonada",
    "enxaguarse": "enjuagarse",
    "enxalvegado": "enjalbegado",
    "enxalvegar": "enjalbegar",
    "enxerto": "injerto",
    "enxugada": "enjugada",
    "esaminado": "examinado",
    "escacesa": "escasez",
    "escandalisarse": "escandalizarse",
    "escandalo": "escándalo",
    "escaramujar": "escaramuzar",
    "escarnecimiénto": "escarnecimiento",
    "escarnercer": "escarnecer",
    "escases": "escasez",
    "escavajo": "escarabajo",
    "escodriñada": "escudriñada",
    "escojedor": "escogedor",
    "escondedijo": "escondrijo",
    "escondiendolas": "escondiéndolas",
    "escovajo": "escobajo",
    "escribania": "escribanía",
    "escrivo": "escribo",
    "eslo": "es lo",
    "espezo": "espeso",
    "espital": "hospital",
    "esprimida": "exprimida",
    "espurgar": "expurgar",
    "estebado": "estevado",
    "estencia": "esencia",
    "estendidos": "extendidos",
    "fanfarron": "fanfarrón",
    "fiandole": "fiándole",
    "friamente": "fríamente",
    "gentilica": "gentílica",
    "gentio": "gentío",
    "governalle": "gobernalle",
    "guardán": "guardan",
    "halagándo": "halagando",
    "hara": "hará",
    "hómbros": "hombros",
    "juntán": "juntan",
    "júntamente": "juntamente",
    "legacia": "legacía",
    "levántarse": "levantarse",
    "lios": "líos",
    "lomesmo": "lo mismo",
    "malefico": "maléfico",
    "matandole": "matándole",
    "mayordomia": "mayordomía",
    "menoria": "minoría",
    "mirandole": "mirándole",
    "mirándo": "mirando",
    "mándados": "mandados",
    "mánjar": "manjar",
    "mémbrudo": "membrudo",
    "méndigar": "mendigar",
    "nacar": "nácar",
    "oido": "oído",
    "panaderia": "panadería",
    "parlon": "parlón",
    "perdio": "perdió",
    "poesia": "poesía",
    "poniendolo": "poniéndolo",
    "prosperamente": "prósperamente",
    "prudéncia": "prudencia",
    "pulgon": "pulgón",
    "quebrántar": "quebrantar",
    "quemazon": "quemazón",
    "recreandolo": "recreándolo",
    "regalandole": "regalándole",
    "retozon": "retozón",
    "rufianeria": "rufianería",
    "septimo": "séptimo",
    "solia": "solía",
    "sémbrada": "sembrada",
    "talamo": "tálamo",
    "taner": "tañer",
    "tardon": "tardón",
    "tenian": "tenían",
    "tesoneria": "tesonería",
    "tios": "tíos",
    "tonteria": "tontería",
    "tornandola": "tornándola",
    "torzon": "torzón",
    "tónto": "tonto",
    "ultimamente": "últimamente",
    "venciendolo": "venciéndolo",
    "véncida": "vencida",
    "vénde": "vende",
    "vénder": "vender",
    "yendosele": "yéndosele",
    "éncima": "encima",
    "ñudos": "nudos",
    "acaudilladagente": "acaudillada gente",
    "doblegadacosa": "doblegada cosa",
    "elfuego": "el fuego",
    "enmucho": "en mucho",
    "enpaciencia": "en paciencia",
    "enprecio": "en precio",
    "generalmentete": "generalmente",
    "lahorca": "la horca",
    "laprimera": "la primera",
    "losque": "los que",
    "malafama": "mala fama",
    "misangre": "mi sangre",
    "nosiba": "nociva",
    "secome": "se come",
    "seha": "se ha",
    "semete": "se mete",
    "sepuede": "se puede",
    "seralabado": "ser alabado",
    "sevicio": "servicio",
    "sinremedio": "sin remedio",
    "sobreotro": "sobre otro",
    "tierramontañosa": "tierra montañosa",
    "unparto": "un parto",
    # Next visible cluster: high-confidence accent restoration and modern spellings.
    "acucharrarse": "acuchararse",
    "alfayáte": "alfayate",
    "almadana": "almádena",
    "antonomasticamente": "antonomásticamente",
    "arcoiris": "arcoíris",
    "arevatiña": "arrebatiña",
    "arreburujada": "arrebujada",
    "empederneserse": "empedernirse",
    "empeoramiénto": "empeoramiento",
    "emplazamiénto": "emplazamiento",
    "enconamiénto": "enconamiento",
    "enforrada": "forrada",
    "engastonado": "engastado",
    "enténder": "entender",
    "escarpin": "escarpín",
    "escondiendola": "escondiéndola",
    "estirandolos": "estirándolos",
    "excomunion": "excomunión",
    "fantasia": "fantasía",
    "fingimiénto": "fingimiento",
    "firmándo": "firmando",
    "forzandole": "forzándole",
    "freirse": "freírse",
    "generico": "genérico",
    "glotoneria": "glotonería",
    "gramatico": "gramático",
    "guiandolo": "guiándolo",
    "hambriénto": "hambriento",
    "herren": "herrén",
    "hospederia": "hospedería",
    "hámbrear": "hambrear",
    "hénder": "hender",
    "indigestion": "indigestión",
    "interes": "interés",
    "jubon": "jubón",
    "juntandose": "juntándose",
    "lactea": "láctea",
    "lastimandose": "lastimándose",
    "lexia": "lejía",
    "llevarsela": "llevársela",
    "llorosaménte": "llorosamente",
    "manoseandola": "manoseándola",
    "mecanico": "mecánico",
    "merecimiénto": "merecimiento",
    "mugro": "mugrón",
    "máncebo": "mancebo",
    "mánchar": "manchar",
    "negligéncia": "negligencia",
    "niñerias": "niñerías",
    "parandose": "parándose",
    "pellejeria": "pellejería",
    "perdigon": "perdigón",
    "pescaderia": "pescadería",
    "poniendola": "poniéndola",
    "poniendole": "poniéndole",
    "postrandose": "postrándose",
    "preténdia": "pretendía",
    "príncipal": "principal",
    "príncipalménte": "principalmente",
    "pímpollo": "pimpollo",
    "púnta": "punta",
    "quebrarseme": "quebrárseme",
    "rabano": "rábano",
    "recibio": "recibió",
    "redóndez": "redondez",
    "renglon": "renglón",
    "riñon": "riñón",
    "salpicon": "salpicón",
    "sentenciándo": "sentenciando",
    "siezo": "sieso",
    "sortilega": "sortílega",
    "sotano": "sótano",
    "sénténcia": "sentencia",
    "tabano": "tábano",
    "talon": "talón",
    "tendra": "tendrá",
    "teniendose": "teniéndose",
    "tisica": "tísica",
    "tisico": "tísico",
    "tollida": "tullida",
    "traida": "traída",
    "turron": "turrón",
    "témpestad": "tempestad",
    "témplado": "templado",
    "téndida": "tendida",
    "vencimiénto": "vencimiento",
    "verdescuro": "verde oscuro",
    "ámbas": "ambas",
    "émbargo": "embargo",
    "éngordada": "engordada",
    "acéza": "aceza",
    "acézo": "acezo",
    "acóntecer": "acontecer",
    "afan": "afán",
    "aflojandoles": "aflojándoles",
    "aguijandolo": "aguijándolo",
    "ahogamiénto": "ahogamiento",
    "albeiteria": "albeitería",
    "alfilér": "alfiler",
    "alguién": "alguien",
    "almoháza": "almohaza",
    "amigableménte": "amigablemente",
    "amontonarselo": "amontonárselo",
    "anadir": "añadir",
    "antepie": "antepié",
    # Next visible cluster: count-2/3 accent fixes, clear fusions, and malformed OCR fragments.
    "ahina": "aína",
    "apardeti": "a par de ti",
    "apartadaménte": "apartadamente",
    "apedreandose": "apedreándose",
    "apiedralodo": "a piedra y lodo",
    "arreburujar": "arrebujar",
    "aserrin": "aserrín",
    "asperas": "ásperas",
    "astrologia": "astrología",
    "atandola": "atándola",
    "atronarseme": "atronárseme",
    "auno": "a uno",
    "cacheton": "cachetón",
    "caersele": "caérsele",
    "calámbre": "calambre",
    "cartabon": "cartabón",
    "catedratico": "catedrático",
    "cercania": "cercanía",
    "ceñian": "ceñían",
    "chocarreria": "chocarrería",
    "cigueña": "cigüeña",
    "clerecia": "clerecía",
    "cofradia": "cofradía",
    "colica": "cólica",
    "comenzo": "comenzó",
    "cometi": "cometí",
    "concavo": "cóncavo",
    "copiandola": "copiándola",
    "costúmbre": "costumbre",
    "costúmbres": "costumbres",
    "crucifixion": "crucifixión",
    "crudia": "cruda",
    "créer": "creer",
    "cubriendola": "cubriéndola",
    "cubriendolo": "cubriéndolo",
    "cánsado": "cansado",
    "cómpras": "compras",
    "cómpas": "compás",
    "cómprar": "comprar",
    "cóncierto": "concierto",
    "cóndición": "condición",
    "cónfiado": "confiado",
    "cónjuración": "conjuración",
    "cónsejero": "consejero",
    "cóntiénda": "contienda",
    "cóntrario": "contrario",
    "cónténtamiénto": "contentamiento",
    "cúmplido": "cumplido",
    "cúmplir": "cumplir",
    "demánda": "demanda",
    "derréngado": "derrengado",
    "derréngar": "derrengar",
    "desañudada": "desanudada",
    "desconcertarselos": "desconcertárselos",
    "desconcertarseme": "desconcertárseme",
    "descóncertarse": "desconcertarse",
    "desercar": "descercar",
    "desleido": "desleído",
    "desméntir": "desmentir",
    "desposeido": "desposeído",
    "despúntar": "despuntar",
    "destróncar": "destroncar",
    "destémplanza": "destemplanza",
    "destémplar": "destemplar",
    "deséntonar": "desentonar",
    "deteniendose": "deteniéndose",
    "diligénte": "diligente",
    "dobladaménte": "dobladamente",
    "doliendose": "doliéndose",
    "dulceménte": "dulcemente",
    "déntro": "dentro",
    "edadtener": "tener edad",
    "emprestido": "empréstito",
    "encasa": "en casa",
    "encenegado": "encenagado",
    "encéndida": "encendida",
    "enfermeria": "enfermería",
    "enganandole": "engañándole",
    "enganar": "engañar",
    "engastonada": "engastada",
    "ensanchamiénto": "ensanchamiento",
    "enternecimiénto": "enternecimiento",
    "entomecerme": "entumecérseme",
    "entomecersele": "entumecérsele",
    # Next visible cluster: old b/v/x/j/h spellings, accents, and fused words.
    "estacadade": "estacada de",
    "estitica": "estíptica",
    "estorno": "estornino",
    "estrangurria": "estranguria",
    "estranjeros": "extranjeros",
    "estrivar": "estribar",
    "eucandilar": "encandilar",
    "eucóntrarse": "encontrarse",
    "exambre": "enjambre",
    "exeder": "exceder",
    "experiméntada": "experimentada",
    "exsaminada": "examinada",
    "exsaminado": "examinado",
    "faisan": "faisán",
    "faxada": "fajada",
    "finandose": "finándose",
    "frie": "fríe",
    "fructifero": "fructífero",
    "fundaménto": "fundamento",
    "gabilan": "gavilán",
    "gallido": "gallillo",
    "ganzua": "ganzúa",
    "genericamente": "genéricamente",
    "gramatica": "gramática",
    "gruezo": "grueso",
    "guardandolo": "guardándolo",
    "haciendole": "haciéndole",
    "haciendolo": "haciéndolo",
    "hagase": "hágase",
    "haversele": "habérsele",
    "harpa": "arpa",
    "hechandolas": "echándolas",
    "heregia": "herejía",
    "herror": "error",
    "hevilla": "hebilla",
    "hevilleta": "hebilleta",
    "hildalgo": "hidalgo",
    "hipochresia": "hipocresía",
    "holer": "oler",
    "honrable": "honorable",
    "hómbres": "hombres",
    "hónra": "honra",
    "imitandola": "imitándola",
    "immenso": "inmenso",
    "incharse": "hincharse",
    "inchazon": "hinchazón",
    "inconcideradamente": "inconsideradamente",
    "inconuersable": "inconversable",
    "inhabil": "inhábil",
    "instincto": "instinto",
    "instrución": "instrucción",
    "interualos": "intervalos",
    "intrumento": "instrumento",
    "jaguei": "jagüey",
    "jarave": "jarabe",
    "javalí": "jabalí",
    "jicama": "jícama",
    "juderia": "judería",
    "judia": "judía",
    "judicio": "juicio",
    "jugedor": "jugador",
    "juztisia": "justicia",
    "júnta": "junta",
    "júntar": "juntar",
    "júntera": "juntera",
    "labadoras": "lavadoras",
    "labadores": "lavadores",
    "labatorio": "lavatorio",
    "labamiento": "lavamiento",
    "laboca": "la boca",
    "laderra": "ladera",
    "lapunta": "la punta",
    "laqual": "la cual",
    "largaménte": "largamente",
    "latierra": "la tierra",
    "laud": "laúd",
    "lavida": "la vida",
    "ledar": "le dar",
    "libello": "libelo",
    "liensos": "lienzos",
    "linge": "linaje",
    "linpia": "limpia",
    "llamer": "lamer",
    "llanten": "llantén",
    "llerva": "hierba",
    # Next visible cluster: old spellings and accents from m/n/o/p rows.
    "mostrandolo": "mostrándolo",
    "moxicones": "mojicones",
    "mozca": "mosca",
    "muchisimas": "muchísimas",
    "mugerilmente": "mujerilmente",
    "mugron": "mugrón",
    "murmuravan": "murmuraban",
    "murmuron": "murmurón",
    "máncebia": "mancebía",
    "mándar": "mandar",
    "mántenimiénto": "mantenimiento",
    "nabaja": "navaja",
    "nabajon": "navajón",
    "naci": "nací",
    "nacimiénto": "nacimiento",
    "nebar": "nevar",
    "negregrecer": "ennegrecer",
    "nigromantico": "nigromántico",
    "niñes": "niñez",
    "nogustosa": "no gustosa",
    "nonbrar": "nombrar",
    "nvca": "nuca",
    "ochénta": "ochenta",
    "ofrecerseme": "ofrecérseme",
    "olbidado": "olvidado",
    "olbido": "olvido",
    "oncio": "oficio",
    "osiempre": "o siempre",
    "osiosamente": "ociosamente",
    "ospedaje": "hospedaje",
    "ospedar": "hospedar",
    "ospederia": "hospedería",
    "ostinadamente": "obstinadamente",
    "otor": "otro",
    "oviese": "hubiese",
    "paba": "pava",
    "pabo": "pavo",
    "paboroso": "pavoroso",
    "pagiza": "pajiza",
    "panederia": "panadería",
    "panturrilludo": "pantorrilludo",
    "pararseme": "parárseme",
    "pareciendose": "pareciéndose",
    "partiendole": "partiéndole",
    "paréntesco": "parentesco",
    "pateándo": "pateando",
    "paxarico": "pajarico",
    "paxarillo": "pajarillo",
    "pedra": "piedra",
    "pegarseme": "pegárseme",
    "pelliscar": "pellizcar",
    "pensava": "pensaba",
    "peoria": "peoría",
    "perayle": "pelaire",
    "peresosa": "perezosa",
    "perfecionar": "perfeccionar",
    "perficionar": "perfeccionar",
    "permaneciénte": "permaneciente",
    "perplexo": "perplejo",
    "perrochiano": "parroquiano",
    "persuación": "persuasión",
    "peruersos": "perversos",
    "pescueso": "pescuezo",
    "pezcuezo": "pescuezo",
    "piedreria": "pedrería",
    "pifano": "pífano",
    "pifanos": "pífanos",
    "pipollo": "pimpollo",
    "pizar": "pisar",
    "plegandola": "plegándola",
    "pleitesia": "pleitesía",
    "plumage": "plumaje",
    "plántar": "plantar",
    "podon": "podón",
    "ponsoñoso": "ponzoñoso",
    "ponzonosa": "ponzoñosa",
    "ponén": "ponen",
    "porarte": "por arte",
    "porla": "por la",
    "portatil": "portátil",
    "portánto": "por tanto",
    "porvengarse": "por vengarse",
    "porvéntura": "por ventura",
    "posima": "pócima",
    "preguntádo": "preguntado",
    "prelacia": "prelacía",
    "pribar": "privar",
    "probocado": "provocado",
    "prohibe": "prohíbe",
    "prolixamente": "prolijamente",
    "promptitud": "prontitud",
    "proprias": "propias",
    "proteruia": "protervia",
    "proteruo": "protervo",
    "provocandole": "provocándole",
    "conoscido": "conocido",
    "soi": "soy",
    "uacar": "vacar",
    # Next visible cluster: q/r/s/t/u/v/y/z historical spellings and accents.
    "quajarse": "cuajarse",
    "quantomas": "cuanto más",
    "quarta": "cuarta",
    "quaxada": "cuajada",
    "quebrandolo": "quebrándolo",
    "quebro": "quebró",
    "quexosa": "quejosa",
    "ragalar": "regalar",
    "raida": "raída",
    "rascandose": "rascándose",
    "rascuñado": "rasguñado",
    "rascuñarme": "rasguñarme",
    "rasimo": "racimo",
    "raygar": "arraigar",
    "reberencia": "reverencia",
    "rebusnar": "rebuznar",
    "recevir": "recibir",
    "recibira": "recibirá",
    "recidencia": "residencia",
    "recogendolas": "recogiéndolas",
    "recogiendolas": "recogiéndolas",
    "recompesar": "recompensar",
    "reconsiliar": "reconciliar",
    "redemir": "redimir",
    "reflegandolo": "refregándolo",
    "refrigan": "refriegan",
    "regañon": "regañón",
    "rehen": "rehén",
    "relampagear": "relampaguear",
    "remosarse": "remozarse",
    "rempujon": "rempujón",
    "rempuxar": "rempujar",
    "renir": "reñir",
    "renpujar": "rempujar",
    "repartimiénto": "repartimiento",
    "reprehénder": "reprender",
    "representandoseme": "representándoseme",
    "requeson": "requesón",
    "requezon": "requesón",
    "rescebir": "recibir",
    "resgatando": "rescatando",
    "residéncia": "residencia",
    "restreñido": "estreñido",
    "resualar": "resbalar",
    "resumarse": "rezumarse",
    "resuscitado": "resucitado",
    "retosar": "retozar",
    "retraherse": "retraerse",
    "revanada": "rebanada",
    "revez": "revés",
    "revolbedor": "revolvedor",
    "revozar": "rebozar",
    "rezonglon": "rezonglón",
    "rian": "rían",
    "riquesas": "riquezas",
    "riñendolo": "riñéndolo",
    "rofianeria": "rufianería",
    "rollisas": "rollizas",
    "rolliso": "rollizo",
    "romanse": "romance",
    "ronceria": "roncería",
    "rrastrillar": "rastrillar",
    "rrato": "rato",
    "rrempujar": "rempujar",
    "rreyes": "reyes",
    "rrueda": "rueda",
    "réndir": "rendir",
    "réngleras": "rengleras",
    "réntar": "rentar",
    "sacandoles": "sacándoles",
    "sacraméntos": "sacramentos",
    "sacándo": "sacando",
    "sanctiago": "santiago",
    "sangrandor": "sangrador",
    "sarpollirse": "sarpullirse",
    "satanas": "satanás",
    "satisfación": "satisfacción",
    "satisfasiendo": "satisfaciendo",
    "savandija": "sabandija",
    "secresto": "secuestro",
    "sedexa": "se deja",
    "semenjante": "semejante",
    "senalar": "señalar",
    "senales": "señales",
    "senor": "señor",
    "senoria": "señoría",
    "senorear": "señorear",
    "sensos": "censos",
    "seron": "serón",
    "sevénde": "se vende",
    "siendolo": "siéndolo",
    "siguiense": "síguense",
    "soberuecer": "ensoberbecer",
    "solicitamente": "solícitamente",
    "soterranamente": "subterráneamente",
    "sosobrar": "zozobrar",
    "subjeción": "sujeción",
    "submergirse": "sumergirse",
    "subtileza": "sutileza",
    "sufrimiento": "sufrimiento",
    "surdamente": "sordamente",
    "turbadaménte": "turbadamente",
    "turvar": "turbar",
    "turvio": "turbio",
    "tántos": "tantos",
    "témblar": "temblar",
    "uedar": "vedar",
    "umeda": "húmeda",
    "umedecerse": "humedecerse",
    "unguentos": "ungüentos",
    "urina": "orina",
    "urinas": "orinas",
    "vagre": "bagre",
    "vallena": "ballena",
    "vallestear": "ballestear",
    "vanarse": "bañarse",
    "vanco": "banco",
    "vanimo": "ánimo",
    "vedriada": "vidriada",
    "veintitres": "veintitrés",
    "vellacos": "bellacos",
    "vellon": "vellón",
    "veodo": "beodo",
    "verdecica": "verdecita",
    "verenda": "vereda",
    "verto": "huerto",
    "vesar": "besar",
    "veses": "veces",
    "vexación": "vejación",
    "viente": "viento",
    "vinedo": "viñedo",
    "visnieta": "bisnieta",
    "visnieto": "bisnieto",
    "visojo": "bisojo",
    "vispera": "víspera",
    "vocado": "bocado",
    "volatile": "volátil",
    "voras": "voraz",
    "vuetas": "vueltas",
    "véndimiar": "vendimiar",
    "véndén": "venden",
    "véntaja": "ventaja",
    "xabonado": "jabonado",
    "xarro": "jarro",
    "xícara": "jícara",
    "xícaras": "jícaras",
    "ycostumbre": "y costumbre",
    "yelada": "helada",
    "yendoseme": "yéndoseme",
    "yengaño": "y engaño",
    "yubilado": "jubilado",
    "yuntera": "juntera",
    "yurar": "jurar",
    "yuzgado": "juzgado",
    "yuzgar": "juzgar",
    "yéndo": "yendo",
    "zabulle": "zambulle",
    "zabullido": "zambullido",
    "zanzamora": "zarzamora",
    "zavana": "sabana",
    "zazonando": "sazonando",
    "zurron": "zurrón",
    "ádonde": "adonde",
    "ánda": "anda",
    "éncogido": "encogido",
    "éncubrir": "encubrir",
    "énmiénda": "enmienda",
    "éntero": "entero",
    "musico": "músico",
    "viguela": "vihuela",
    "vivela": "vihuela",
}

PHRASE_REPLACEMENTS = {
    r"\bputañar\b": "putañear (arcaico: fornicar)",
    r"\bputañear\b(?!\s*\(arcaico:)": "putañear (arcaico: fornicar)",
    r"\bcontagión\b(?!\s*\(arcaico:)": "contagión (arcaico: contagio)",
    r"\bcircunstar\b(?!\s*\(arcaico:)": "circunstar (arcaico: rodear o circundar)",
    r"\bromadizante\b(?!\s*\(arcaico:)": "romadizante (arcaico: con catarro)",
    r"\btristear\b(?!\s*\(arcaico:)": "tristear (arcaico: estar triste)",
    r"\bprovocar a otro aira\b": "provocar a otro a ira",
    r"\bprovocar aira\b": "provocar a ira",
    r"^cortez$": "cortés",
    r"\bcauteloso;\s*cortez;\s*prudente\b": "cauteloso; cortés; prudente",
    r"\bcarnes tollendas\b(?!\s*\(arcaico:)": "carnes tollendas (arcaico: carnestolendas)",
    r"\bcincuesma\b(?!\s*\(arcaico:)": "cincuesma (arcaico: Pentecostés)",
    r"\bde contino\b(?!\s*\(arcaico:)": "de contino (arcaico: continuamente)",
    r"\bderrabado\b(?!\s*\(arcaico:)": "derrabado (arcaico: desrabado o sin cola)",
    r"\blobadado\b(?!\s*\(arcaico:)": "lobadado (arcaico: alobadado)",
    r"\bpremido\b(?!\s*\(arcaico:)": "premido (arcaico: oprimido o apretado)",
    r"\bpremido \(arcaico: oprimido o apretado\) o apretado\b": "premido (arcaico: oprimido), o apretado",
    r"\bhermosear\s+o\s+hermosear\s+algo\b": "hermosear algo",
    r"\bal cavo de la cual\b": "al cabo de la cual",
    r"\bdesmontar otalar montes\b": "desmontar o talar montes",
    r"\ben calvecer\b": "encalvecer",
    r"\bdesgustoy\b": "disgusto y",
    r"\batollado po otro\b": "atollado por otro",
    r"\bde veinte uno\b": "de veintiuno",
    r"\bde veinte dos\b": "de veintidós",
    r"\bdesi mismo\b": "de sí mismo",
    r"\bdando con el por esos\b": "dando con él por esos",
    r"\bse lastimo\b": "se lastimó",
    r"\bdestruición\b(?!\s*\(arcaico:)": "destruición (arcaico: destrucción)",
    r"\bforgicar\b(?!\s*\(arcaico:)": "forgicar (arcaico: fingir o inventar)",
    r"\binfuriar\b(?!\s*\(arcaico:)": "infuriar (arcaico: enfurecer)",
    r"\bmedidura\b(?!\s*\(arcaico:)": "medidura (arcaico: medida)",
    r"\bniñeta\b(?!\s*\(arcaico:)": "niñeta (arcaico: pupila)",
    r"\bques del\?\.\s*o cual es\?\.": "qué es de él? o cuál es?",
    r"\blo ques está\b": "lo que está",
    r"\bsecrestación\b(?!\s*\(arcaico:)": "secrestación (arcaico: secuestro)",
    r"\bventajar dar\b": "dar ventaja",
    r"\bventajar,\s*dar\b": "ventajar (arcaico: aventajar), dar",
    r"\bvilecerse\b(?!\s*\(arcaico:)": "vilecerse (arcaico: envilecerse o bajar de valor)",
    r"\bcaiga entierra\b": "caiga en tierra",
    r"\bcaer entierra\b": "caer en tierra",
    r"\bda consigo entierra\b": "da consigo en tierra",
    r"\bderribar a otro entierra\b": "derribar a otro en tierra",
    r"\s*\*\s*a cheval sur deux pages\b": "",
    r"\bhenchir\s+lo\s+que\s+falta,?\s+o\s+henchir\b": "henchir lo que falta",
    r"\bhenchir\s*[,;]?\s*o\s+henchir\b": "henchir",
    r"\bfiscal\s*[,;]?\s*o\s+fiscal\b": "fiscal",
    r"\blluvia\s*[,;]?\s*o\s+lluvia\b": "lluvia",
    r"\bpellizcar\s*[,;]?\s*o\s+pellizcar\b": "pellizcar",
    r"\bplumas\s+trupial\b": "plumas de trupial",
    r"\btañer\s+\[tañer\]": "tañer",
    r"\bcañas\s+jícaras\b": "cañas, jícaras",
    r"\ben hiesta\b": "enhiesta",
    r"\bsemiente,?\s+o\s+simiente\b": "simiente",
    r"\bpotrico\b(?!\s*\(arcaico:)": "potrico (arcaico: potrillo)",
    r"\banimos\s+o,": "animoso,",
    r"\bcalos fríos tener\b": "tener calofríos",
    r"\ben crucijada de caminos\b": "encrucijada de caminos",
    r"\bdesasosega da persona\b": "desasosegada persona",
    r"\bempadronam\(ien\(to\b": "empadronamiento",
    r"\bengrandecim\(ien\(to\b": "engrandecimiento",
    r"\bgolria\b": "gloria",
    r"\bse empresto\b": "se prestó",
    r"\byo empresto\b": "yo presto",
    r"\bengañar\s+\[engañar\]": "engañar",
    r"\bengañar embaucar\b": "engañar, embaucar",
    r"\bensañarse\s+\[ensañarse\]": "ensañarse",
    r"\basetear o flechar\.\[aseatear\]": "asaetear o flechar.",
    r"\bsoltarsemela palabra\b": "soltárseme la palabra",
    r"\bencontinenti\b(?!\s*\(arcaico:)": "encontinenti (arcaico: inmediatamente)",
    r"\benfucia\b(?!\s*\(arcaico:)": "enfucia (arcaico: confianza)",
    r"\bprestido\b(?!\s*\(arcaico:)": "préstido (arcaico: préstamo)",
    r"\bparde\b": "par de",
    r"\bponzoñar de víbora\b": "ponzoña de víbora",
    r"\bcurir herir\b": "herir",
    r"\bcurir uno con otro\b": "herirse uno con otro",
    r"\bhacer esterir a alguna\b": "hacer estéril a alguna",
    r"\bconfaxa\b": "con faja",
    r"\bgarta\b": "garganta",
    r"\bhechichos\b": "hechizos",
    r"\btomandolas\b": "tomándolas",
    r"\btornandolas\b": "tornándolas",
    r"\botres\b": "o tres",
    r"\benaltoy\b": "en alto y",
    r"\barecoger\b": "a recoger",
    r"\bhava\b": "haba",
    r"\bhaba\s+\[haba\]\s+legumbre\b": "haba legumbre",
    r"\bjesu cristo\b": "jesucristo",
    r"\bjasar sangre jasando\b": "sajar sangre sajando",
    r"\blargam\(en\(te\b": "largamente",
    r"\blargam\(en\)te\b": "largamente",
    r"\blhaz\b": "la haz",
    r"\blahaz\b": "la haz",
    r"\binstrum\(en\(to\b": "instrumento",
    r"\binstrum\(en\)to\b": "instrumento",
    r"\bnombrome yo\b": "me nombro yo",
    r"\benochenta\b": "en ochenta",
    r"\bodixo\b": "o dijo",
    r"\bolinde\b": "o linde",
    r"\bollaso cosas\b": "ollas o cosas",
    r"\bomalla\b": "o malla",
    r"\boser\b": "o ser",
    r"\botronera\b": "o tronera",
    r"\boviene\b": "o viene",
    r"\bnatura les\b": "naturales",
    r"\bporle haber quitado alguna parte del\b": "por haberle quitado alguna parte de él",
    r"\bcaerse le lasbauas\b": "caérsele las babas",
    r"\bsocorrome yo\b": "me socorro yo",
    r"\bbañarse\s+\[bañarse\]": "bañarse",
    r"\bseñorear\s+\[señorear\]": "señorear",
    r"\bturbar o turbar\b": "turbar",
    r"\beñlagua\b": "en el agua",
    r"\bpece grande\b": "pez grande",
    r"\bdisfraccase dese\b": "disfrázcase de ese",
    r"\bse salvo\b": "se salvó",
    r"\btolondrón\s+tolondrón\b": "tolondrón",
    r"\btolondrón\.\s*tolon\b": "tolondrón",
    r"\bvidrio\s*[,;]?\s*o\s+vidrio\b": "vidrio",
    r"\bvidrio\s*;\s*vidrio\b": "vidrio",
    r"\bdesdel\s+un\b": "desde un",
    r"\bdesdel\b": "desde el",
    r"\bgeneralm\(en\(te\b": "generalmente",
    r"\bgeneralm\(en\)te\b": "generalmente",
    r"\bquan\s+(?=(?:buena|bueno|grande|justo)\b)": "cuán ",
    r"\bpellizco\s*[,;]?\s*o\s+pellizco\b": "pellizco",
    r"\bveinti\s+una\b": "veintiuna",
    r"\bveinti\s+dos\b": "veintidós",
    r"\bveinti\s+tres\b": "veintitrés",
    r"\bveinti\s+cuatro\b": "veinticuatro",
    r"\bveinti\s+cinco\b": "veinticinco",
    r"\bveinti\s+seis\b": "veintiséis",
    r"\bveinti\s+siete\b": "veintisiete",
    r"\bveinti\s+ocho\b": "veintiocho",
    r"\bveinti\s+nueve\b": "veintinueve",
    r"\bmescladam\(en\)te\b": "mezcladamente",
    r"\bmescladam\(en\(te\b": "mezcladamente",
    r"\bhalaga de halagüeño\b": "halago de halagüeño",
    r"\bhave \[hava\] legumbre\b": "haba [hava] legumbre",
    r"\bazacar agua\b": "azacar (arcaico: acarrear agua) agua",
    r"\bcabezpelado\b(?!\s*\(arcaico:)": "cabezpelado (arcaico: calvo o de pocos cabellos)",
    r"\bchanzcando\b(?!\s*\(arcaico:)": "chanzcando (arcaico: chanceando, con chanzas)",
    r"\bdemediado\b(?!\s*\(arcaico:)": "demediado (arcaico: reducido a la mitad)",
    r"\bderrabada ave\b(?!\s*\(arcaico:)": "derrabada (arcaico: desrabada o sin cola) ave",
    r"\bdesenseñado\b(?!\s*\(arcaico:)": "desenseñado (arcaico: que olvidó lo aprendido)",
    r"\bendemal\b(?!\s*\(arcaico:)": "ende mal (arcaico: gozo por el mal ajeno)",
    r"\bafrenta, baldón o enjabonamiento\b(?!\s*\(arcaico:)": "afrenta, baldón o enjabonamiento (arcaico: afrenta o baldón)",
    r"\bafrenta, baldón, o enjabonamiento\b(?!\s*\(arcaico:)": "afrenta, baldón, o enjabonamiento (arcaico: afrenta o baldón)",
    r"\benjabonamiento tal\b": "enjabonamiento (arcaico: afrenta o baldón) tal",
    r"\bfloretón\b(?!\s*\(arcaico:)": "floretón (arcaico: golpe con los dedos)",
    r"\bfornecimi[eé]nto\b(?!\s*\(arcaico:)": "fornecimiento (arcaico: fortificación)",
    r"\bgloriación\b(?!\s*\(arcaico:)": "gloriación (arcaico: glorificación)",
    r"\bhomiciano\b(?!\s*\(arcaico:)": "homiciano (arcaico: homicida)",
    r"\bomiciano\b": "homiciano (arcaico: homicida)",
    r"\braez cosa de hacer\b": "raez (arcaico: fácil) cosa de hacer",
}

RECORD_REPLACEMENTS = {
    # Residue pass: row-specific fixes where a global token replacement would
    # overreach or where the answer depends on sibling entries.
    "17-bnf-362:002618": {"asens": "asens (junco gordo y largo)"},
    "1780-bnf-361:009206": {
        "desasosegada persona sin reposo e inquieta": "persona desasosegada (inquieta y sin reposo)",
    },
    "1780-bnf-361:008144": {"arregarse": "alargarse"},
    "1765-cortes-y-zedeno:000475": {"calillar": "calillar (arcaico: curar con calilla)"},
    "1598-tezozomoc:000508": {"chilpinole": "chilpinole (náhuatl: pinole con chile)"},
    "1580-sahagun-maynez:001497": {"cuervero": "cuevero (raposa)"},
    "1780-clavijero:002926": {"diablería": "diablería (cosa diabólica)"},
    "1780-bnf-361:020228": {"encaso": "encaso (sentido incierto)"},
    "17-bnf-362:001269": {"enmantecarse": "enmantecarse (arcaico: engrasarse)"},
    "17-bnf-362:001779": {"hijanes": "ijares"},
    "1547-olmos-v:001070": {"honoratur": "honoratur (latín: ser honrado)"},
    "1547-olmos-v:001071": {"honoratur": "honoratur (latín: ser honrado)"},
    "1580-sahagun-maynez:000946": {"martinetón": "martinetón (ave de agüero)"},
    "1780-clavijero:001329": {"nutrie": "nutria"},
    "1598-tezozomoc:001332": {"quechtepol": "quechtepolli (náhuatl: pescuezo o cerviz)"},
    "1547-olmos-g:000363": {"riome": "me río"},
    "1547-olmos-g:000779": {"riome": "me río"},
    "17-bnf-362:001384": {"tartaroso": "tartaroso (con tártaro)"},
    "1547-olmos-v:000366": {"tenpestuosum": "tempestuosum (latín: inquieto o agitado)"},
    "1547-olmos-v:000367": {"tenpetuosum": "tempestuosum (latín: inquieto o agitado)"},
    "1551-95-documentos-nahuas-de-la-ciudad-de-mexico:002658": {
        "tepisque": "tepixque (náhuatl: guarda de gente)",
    },
    "1551-95-documentos-nahuas-de-la-ciudad-de-mexico:000102": {
        "zagueta": "zagueta (arcaico: prenda de piel)",
    },
    "1547-olmos-v:001379": {"jnpregnatur": "impregnatur (latín: empreñarse)"},
    "1780-clavijero:001145": {
        "semipronombre": "semipronombre (prefijo posesivo de tercera persona)",
    },
}

RECORD_EXACT_REPLACEMENTS = {
    # Correct already-applied residue glosses to the source-first annotation
    # convention: normalized term first, explanatory change in parentheses.
    "17-bnf-362:002618": {"junco gordo y largo": "asens (junco gordo y largo)"},
    "1780-bnf-361:009206": {
        "persona inquieta y sin reposo.": "persona desasosegada (inquieta y sin reposo).",
    },
    "1765-cortes-y-zedeno:000475": {
        "curar con calilla": "calillar (arcaico: curar con calilla)",
    },
    "1598-tezozomoc:000508": {
        "pinole con chile": "chilpinole (náhuatl: pinole con chile)",
    },
    "1580-sahagun-maynez:001497": {"raposa": "cuevero (raposa)"},
    "1780-clavijero:002926": {"cosa diabólica": "diablería (cosa diabólica)"},
    "1780-bnf-361:020228": {"sentido incierto": "encaso (sentido incierto)"},
    "17-bnf-362:001269": {"engrasarse": "enmantecarse (arcaico: engrasarse)"},
    "1547-olmos-v:001070": {"ser honrado": "honoratur (latín: ser honrado)"},
    "1547-olmos-v:001071": {"ser honrado": "honoratur (latín: ser honrado)"},
    "1580-sahagun-maynez:000946": {"ave de agüero": "martinetón (ave de agüero)"},
    "1598-tezozomoc:001332": {
        "pescuezo o cerviz": "quechtepolli (náhuatl: pescuezo o cerviz)",
    },
    "17-bnf-362:001384": {"con tártaro": "tartaroso (con tártaro)"},
    "1547-olmos-v:000366": {
        "inquieto o agitado": "tempestuosum (latín: inquieto o agitado)",
    },
    "1547-olmos-v:000367": {
        "inquieto o agitado": "tempestuosum (latín: inquieto o agitado)",
    },
    "1551-95-documentos-nahuas-de-la-ciudad-de-mexico:002658": {
        "guarda de gente": "tepixque (náhuatl: guarda de gente)",
    },
    "1551-95-documentos-nahuas-de-la-ciudad-de-mexico:000102": {
        "prenda de piel": "zagueta (arcaico: prenda de piel)",
    },
    "1547-olmos-v:001379": {"empreñarse": "impregnatur (latín: empreñarse)"},
    "1780-clavijero:001145": {
        "prefijo posesivo de tercera persona": "semipronombre (prefijo posesivo de tercera persona)",
    },
    "1780-bnf-361:021809": {
        "prestar": "putañear (arcaico: fornicar)",
        "putañear": "putañear (arcaico: fornicar)",
    },
}


def token_pattern(token: str) -> re.Pattern[str]:
    return re.compile(rf"(?<![^\W\d_]){re.escape(token)}(?![^\W\d_])", re.I | re.UNICODE)


TOKEN_PATTERNS = [(src.casefold(), token_pattern(src), src, dst) for src, dst in TOKEN_REPLACEMENTS.items()]
PHRASE_PATTERNS = [(re.compile(src, re.I), src, dst) for src, dst in PHRASE_REPLACEMENTS.items()]
RECORD_PATTERNS = {
    record_id: [(src.casefold(), token_pattern(src), src, dst) for src, dst in replacements.items()]
    for record_id, replacements in RECORD_REPLACEMENTS.items()
}
RECORD_REPLACEMENT_LOOKUP = {
    f"{record_id}:{src}": dst
    for record_id, replacements in RECORD_REPLACEMENTS.items()
    for src, dst in replacements.items()
}
RECORD_EXACT_REPLACEMENT_LOOKUP = {
    f"{record_id}:exact:{src}": dst
    for record_id, replacements in RECORD_EXACT_REPLACEMENTS.items()
    for src, dst in replacements.items()
}


def translation_field(row: dict) -> str | None:
    source = row.get("Fuente")
    if source in {"2021 Wimmer", "1992 Karttunen", "V94 Diccionario Global SNP"}:
        return None
    return "Traducción" if "Traducción" in row else None


def apply_replacements(text: str, record_id: str | None = None) -> tuple[str, Counter[str]]:
    changes: Counter[str] = Counter()
    new = text
    record_key = record_id or ""

    exact_replacements = RECORD_EXACT_REPLACEMENTS.get(record_key)
    if exact_replacements and new in exact_replacements:
        src = new
        new = exact_replacements[src]
        changes[f"{record_key}:exact:{src}"] += 1
        return new, changes

    lower_new = new.casefold()
    for needle, pattern, src, dst in RECORD_PATTERNS.get(record_key, []):
        if needle not in lower_new:
            continue
        if dst.casefold() in lower_new:
            continue
        new, count = pattern.subn(dst, new)
        if count:
            changes[f"{record_key}:{src}"] += count
            lower_new = new.casefold()

    for needle, pattern, src, dst in TOKEN_PATTERNS:
        if needle not in lower_new:
            continue
        if dst.casefold() in lower_new:
            continue
        new, count = pattern.subn(dst, new)
        if count:
            changes[src] += count
            lower_new = new.casefold()

    for pattern, src, dst in PHRASE_PATTERNS:
        new, count = pattern.subn(dst, new)
        if count:
            changes[src] += count

    if changes:
        cleaned = re.sub(r" {2,}", " ", new)
        cleaned = re.sub(r" +([,;:.])", r"\1", cleaned).strip()
        if cleaned != new:
            new = cleaned
            changes["spacing after context fix"] += 1

    return new, changes


def iter_rows(path: Path):
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        for line in fh:
            yield json.loads(line)


def write_rows(path: Path, rows: list[dict]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with gzip.open(tmp, "wt", encoding="utf-8", compresslevel=9) as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    tmp.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--data", type=Path, default=DATA_PATH)
    parser.add_argument("--report", type=Path, default=REPORT_PATH)
    args = parser.parse_args()

    rows = []
    reports = []
    changed_rows = 0
    replacement_counts: Counter[str] = Counter()

    for row in iter_rows(args.data):
        field = translation_field(row)
        if field and isinstance(row.get(field), str):
            old = row[field]
            record_id = row.get("record_id") or row.get("id") or row.get("ID")
            new, changes = apply_replacements(old, record_id)
            if new != old:
                changed_rows += 1
                replacement_counts.update(changes)
                reports.append(
                    {
                        "record_id": record_id,
                        "Fuente": row.get("Fuente"),
                        "Lema": row.get("Texto estandarizado") or row.get("Lema"),
                        "field": field,
                        "changes": dict(changes),
                        "old": old,
                        "new": new,
                    }
                )
                if args.apply:
                    row[field] = new
        rows.append(row)

    args.report.parent.mkdir(parents=True, exist_ok=True)
    with args.report.open("w", encoding="utf-8") as fh:
        for report in reports:
            fh.write(json.dumps(report, ensure_ascii=False) + "\n")

    print(f"mode={'apply' if args.apply else 'dry-run'}")
    print(f"changed_rows={changed_rows}")
    print(f"report={args.report}")
    print("top_replacements=")
    for key, count in replacement_counts.most_common(80):
        replacement = (
            TOKEN_REPLACEMENTS.get(key)
            or PHRASE_REPLACEMENTS.get(key)
            or RECORD_REPLACEMENT_LOOKUP.get(key)
            or RECORD_EXACT_REPLACEMENT_LOOKUP.get(key)
            or "<regex>"
        )
        print(f"{key}\t{count}\t->\t{replacement}")

    if args.apply:
        write_rows(args.data, rows)


if __name__ == "__main__":
    main()
